"""Add cards table

Revision ID: 5186b737f927
Revises: c064a6caabc0
Create Date: 2025-08-13 10:03:50.027613

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5186b737f927'
down_revision = 'c064a6caabc0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(length=255), nullable=False),
    sa.Column('emoji', sa.String(length=10), nullable=True),
    sa.Column('value', sa.String(length=50), nullable=False),
    sa.Column('relation', sa.String(length=50), nullable=False),
    sa.Column('img', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_admin', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_admin')

    op.drop_table('cards')
    # ### end Alembic commands ###
