"""empty message

Revision ID: 988817383bc2
Revises: 0763d677d453
Create Date: 2025-07-24 12:49:57.593648

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '988817383bc2'
down_revision = '0763d677d453'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reset_token', sa.String(length=256), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('reset_token')

    # ### end Alembic commands ###
